# Generated by Django 3.2.25 on 2024-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
