# Generated by Django 3.2.25 on 2024-07-04 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_tenant', '0004_auto_20240704_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
